services:
  - type: web
    name: invoice-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app.backend.src.main:app -k uvicorn.workers.UvicornWorker --workers=4"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: redis
          type: redis
          property: connectionString
      - key: AUTH0_DOMAIN
        value: dev-0dghf4l675sx6lf3.us.auth0.com
      - key: AUTH0_AUDIENCE
        value: https://invoice-api/
  - type: worker
    name: invoice-worker-small
    env: python
    startCommand: "celery -A invoice_agent.tasks.worker.celery worker -Q small --concurrency=4"
    autoscale: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: redis
          type: redis
          property: connectionString
  - type: worker
    name: invoice-worker-medium
    env: python
    startCommand: "celery -A invoice_agent.tasks.worker.celery worker -Q medium --concurrency=2"
    autoscale: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: redis
          type: redis
          property: connectionString
  - type: worker
    name: invoice-worker-large
    env: python
    startCommand: "celery -A invoice_agent.tasks.worker.celery worker -Q large --concurrency=1"
    autoscale: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: redis
          type: redis
          property: connectionString
  - type: redis
    name: redis
    plan: standard
  - type: pserv
    name: postgres
    plan: standard
  - type: static
    name: invoice-frontend
    buildCommand: "npm install && npm run build"
    publishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://invoice-api.onrender.com/api
      - key: VITE_AUTH0_DOMAIN
        value: dev-0dghf4l675sx6lf3.us.auth0.com
      - key: VITE_AUTH0_CLIENT_ID
        value: XQQXLyadcsvFGm8SBgNM9yZQFhT8qFCh
      - key: VITE_AUTH0_AUDIENCE
        value: https://invoice-api/
